ledokku/ledokku

server/src/generated/graphql.ts
server/src/graphql/mutations/createApp.ts
server/src/graphql/queries/appLogs.ts
server/src/graphql/queries/index.ts
server/src/graphql/utils.ts
server/src/index.ts
server/src/lib/dokku/apps/logs.ts
server/src/lib/dokku/index.ts

App logs query has arrived. 
Also moved out appName validation outside of create app fn.

feat: add app logs query

---

client/src/pages/activity.tsx
client/src/pages/dashboard.tsx
client/src/pages/metrics.tsx
client/src/pages/settings.tsx

Simply created routes with basic styles, so no 404.

feat(client): add-more-views

---

client/src/pages/app/[appId]/index.tsx
client/src/pages/create-app.tsx
server/src/lib/dokku/apps/logs.ts

Before this branch, we should merge : https://github.com/ledokku/ledokku/pull/46 . 
Multiple issues fixed : 
- refetch dashboard query after new app creation 
- when immediately click on new app, app view works with the "app is still deploying log", which 
changes to 🟢 on the first poll after 2.5 min. This was super exciting to see for the first time. 👀

feat(client): fix newly created app issues

---

client/src/pages/app/[appId]/env.tsx
client/src/pages/app/[appId]/index.tsx
client/src/pages/app/[appId]/settings.tsx
client/src/pages/create-app.tsx
client/src/pages/create-database.tsx

-Env vars hidden by default
-Autocomplete disabled in forms
-AppLogs improved when state is "loading"

feat(client): add hide env vars feature

---

client/src/generated/graphql.tsx
client/src/graphql/queries/setup.graphql
client/src/pages/index.tsx
server/src/config.ts
server/src/generated/graphql.ts
server/src/graphql/queries/index.ts
server/src/graphql/queries/setup.ts
server/src/index.ts

feat: setup screen

---

server/package.json
yarn.lock

@pradel updated apollo-server because of 👇 .

fix(server): upd apollo server

---

client/next.config.js
client/src/config.ts

@pradel as far as I understood, this will solve the issue. 
Only confusing thing to me was that in docs this was mentioned : 
`Runtime configuration won't be available to any page (or component in a page) without **getInitialProps.**` . 
I tried logging the vars, logging in/out and all seemed to work. Am I missing something?

fix(client): add publicRuntimeConfig to nextjs config

---

client/src/pages/home.tsx

closes : https://github.com/ledokku/ledokku/issues/87

feat(client): fix login bug

---

client/src/modules/auth/AuthContext.tsx

fix(client): avatar is not displayed after login

---

client/src/Router.tsx
client/src/pages/app/env.tsx
client/src/pages/app/index.tsx
client/src/pages/app/logs.tsx
client/src/pages/app/settings.tsx
client/src/pages/database/index.tsx
client/src/pages/database/logs.tsx
client/src/pages/database/settings.tsx

Logs moved out to separate view and connect app/db now is in the main view.

feat(client): restructure app and db management views

---

docker-compose.yaml

fix: fix ssh key being destroyed in dev env

---

.prettierignore
CODE_OF_CONDUCT.md
client/package.json
client/src/modules/layout/Header.tsx
client/src/pages/dashboard.tsx
client/tailwind.config.js
package.json
yarn.lock

- use new tailwind react lib
- upgrade tailwind css

chore: use new tailwind react lib

---

client/src/pages/create-database.tsx
client/src/ui/components/Alert.tsx
client/src/ui/components/index.ts

```
<Alert status="error">
<AlertTitle>Request failed</AlertTitle>
<AlertDescription>
{isDokkuPluginInstalledError.message}
</AlertDescription>
</Alert>
```

feat(client): create alert component

---

.github/ISSUE_TEMPLATE/1.Bug_report.md
.github/ISSUE_TEMPLATE/2.Feature_request.md
.github/ISSUE_TEMPLATE/config.yml

for an example go to https://github.com/accounts-js/accounts/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc and click the "new issue" button.

chore: setup github issues template

---

client/codegen.yml
client/package.json
client/src/generated/graphql.tsx
client/src/index.tsx
yarn.lock

Upgraded to @apollo/client mostly based on this: 
https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/

chore(client): update from apollo-client to @apollo/client

---

client/package.json
client/src/pages/app/logs.tsx
server/src/lib/dokku/apps/logs.ts
yarn.lock

Show the same colors as in the terminal, that way errors will be in red etc 😍 
When there are no logs
New view with colors

feat(client): improve app logs view

---

website/docs/installation.mdx

docs: instructions to create volume for ssh key on production

---

client/src/pages/app/index.tsx
client/src/pages/database/index.tsx
client/src/ui/components/Modal.tsx
client/tailwind.config.js

@pradel 
- modal is now more flexible than before
- terminal is now beautifully fitting in in all of the unlinking/linking operations
- some warnings fixed
- found a bug within unlinking and fixed it 
there are still UI things that within modal that can be made better, but for MVP this looks solid enough
closes : https://github.com/ledokku/ledokku/issues/135

feat(client): improve modal component

---

client/src/config.ts
client/src/index.tsx

fix: WS production env for apollo client

---

MAINTAINERS.md
scripts/create-new-release.sh

feat: create release script

---

client/src/pages/app/logs.tsx

fix: fix app view logs when there is an error

---

client/src/pages/app/settings.tsx
client/src/pages/create-database.tsx
client/src/pages/database/settings.tsx
client/src/ui/components/Form.tsx
client/src/ui/components/index.ts

Close #40
I created some form ui comnponents that we can reuse like this:
```tsx
<FormLabel>Database name:</FormLabel>
<FormInput
autoComplete="off"
id="name"
name="name"
value={formik.values.name}
onChange={formik.handleChange}
onBlur={formik.handleBlur}
error={Boolean(formik.errors.name && formik.touched.name)}
/>
{formik.errors.name && formik.touched.name ? (
<FormHelper status="error">{formik.errors.name}</FormHelper>
) : null}
```

feat(client): database form validation

---

server/src/graphql/mutations/loginWithGithub.ts
server/src/index.ts
server/src/lib/dokku/apps/list.ts
server/src/lib/dokku/index.ts
server/src/lib/dokku/plugin/database/links.ts
server/src/lib/dokku/plugin/database/list.ts
server/src/queues/synchroniseServer.ts

Close #143
We start the queue:
- when the first user is created
- when the server start

feat: synchronise ledokku with existing dokku server

---

client/package.json
client/src/modules/layout/Header.tsx
yarn.lock

feat: use accessible dropdown for the top right profile menu

---

client/src/generated/graphql.tsx
client/src/pages/database/settings.tsx
server/src/index.ts

feat(client): improve database info view

---

README.md

closes : https://github.com/ledokku/ledokku/issues/193

chore(docs): add link to getting started guide to README

---

client/src/pages/app/index.tsx

Closes https://github.com/ledokku/ledokku/issues/195
Pretty far from optimal solution, but does the job and as we will refactor these drop downs to HeadlessUI, I thought that it didn't make too much sense to look for elegant solution for now. 
@pradel what is your opinion regarding this?

feat(client): add db creation option to app view

---

client/src/pages/app/index.tsx
server/src/index.ts
server/src/lib/dokku/index.ts
server/src/lib/dokku/plugin/database/link.ts
server/src/lib/dokku/plugin/database/unlink.ts
server/src/queues/linkDatabase.ts
server/src/queues/unlinkDatabase.ts

Closes : https://github.com/ledokku/ledokku/issues/184
And this is also 200th PR 🚀

feat(server): recreate link and unlink functions in dokku lib

---

MAINTAINERS.md
scripts/publish-release.sh

chore: add changelog link to release description

---

scripts/create-new-release.sh
website/docs/upgrade.md
website/sidebars.js

docs: create "how to upgrade" guide

---

website/docs/advanced/configuration.md
website/sidebars.js

docs: create configuration guide

---

website/docs/uninstall.md
website/sidebars.js

Closes : https://github.com/ledokku/ledokku/issues/214

feat(docs): add documentation for uninstalling Ledokku

---

client/package.json
client/src/pages/app/index.tsx
client/src/pages/database/index.tsx
client/src/ui/components/Button.tsx
yarn.lock

Closes : https://github.com/ledokku/ledokku/issues/168

chore(client): switch dropdown from react-select to headless UI

---

.eslintrc.js
client/src/generated/graphql.tsx
client/src/graphql/mutations/addAppProxyPort.graphql
client/src/graphql/mutations/removeAppProxyPort.graphql
client/src/graphql/queries/appProxyPorts.graphql
client/src/modules/appProxyPorts/AddAppProxyPorts.tsx
client/src/modules/appProxyPorts/AppProxyPorts.tsx
client/src/pages/app/settings.tsx
server/src/generated/graphql.ts
server/src/graphql/mutations/addAppProxyPort.ts
server/src/graphql/mutations/index.ts
server/src/graphql/mutations/removeAppProxyPort.ts
server/src/graphql/queries/appProxyPorts.ts
server/src/graphql/queries/index.ts
server/src/index.ts
server/src/lib/dokku/index.ts
server/src/lib/dokku/proxy/ports.ts
server/src/lib/dokku/proxy/portsAdd.ts
server/src/lib/dokku/proxy/portsRemove.ts

Allow user to manage app port via UI

feat: add app port mapping management

---

client/src/pages/app/index.tsx
client/src/pages/create-database.tsx

closes : https://github.com/ledokku/ledokku/issues/196

feat(client): pre populate db name on creation

---

client/src/generated/graphql.tsx
client/src/graphql/mutations/restartApp.graphql
client/src/graphql/subscriptions/restartAppLogs.graphql
client/src/modules/app/AppRestart.tsx
client/src/pages/app/settings.tsx
server/src/generated/graphql.ts
server/src/graphql/mutations/index.ts
server/src/graphql/mutations/restartApp.ts
server/src/index.ts
server/src/lib/dokku/index.ts
server/src/lib/dokku/plugin/database/create.ts
server/src/lib/dokku/process/restart.ts
server/src/queues/restartApp.ts

New settings look screams a bit of redesign as the single column is packed, but that can be done in another PR.

feat(client): add restart app functionality

---

client/package.json
server/package.json
yarn.lock

No breaking changes for us https://github.com/jquense/yup/blob/master/CHANGELOG.md

chore: upgrade yup to 0.31

---

CONTRIBUTING.md

closes : https://github.com/ledokku/ledokku/issues/248

chore(docs): update the prisma migration part in contribution doc

---

client/src/generated/graphql.tsx
client/src/graphql/mutations/rebuildApp.graphql
client/src/graphql/subscriptions/rebuildAppLogs.graphql
client/src/modules/app/AppRebuild.tsx
client/src/pages/app/settings.tsx
server/src/generated/graphql.ts
server/src/graphql/mutations/index.ts
server/src/graphql/mutations/rebuildApp.ts
server/src/index.ts
server/src/lib/dokku/process/rebuild.ts
server/src/queues/rebuildApp.ts

closes : https://github.com/ledokku/ledokku/issues/245

feat(client, server): rebuild app functionality

---

client/src/config.ts

fix: fix websocket connection failing when using https

---

server/src/graphql/mutations/destroyApp.ts

Closes : https://github.com/ledokku/ledokku/issues/263

chore(server): comment out appbuild related part from destroy app fn

---

client/src/pages/app/env.tsx
client/src/pages/app/index.tsx
client/src/pages/app/logs.tsx
client/src/pages/app/settings.tsx

Migrated the header part for all screens and also table part for app index view. 
App main page screenshot :

chore(client): partly migrate app views to chakra

---

client/src/pages/database/index.tsx
client/src/pages/database/logs.tsx
client/src/pages/database/settings.tsx

Similarly to [this PR](https://github.com/ledokku/ledokku/pull/269), I migrated the database views to be aligned with the main layout. 
Closes : https://github.com/ledokku/ledokku/issues/267
Screenshot of index page :

chore(client): partly migrate database views to chakra

---

website/docs/getting-started.mdx
website/docs/installation.mdx
website/docs/uninstall.md

Update links to new dokku domain and latest version in bootstrap script

chore(docs): update version and links

---

client/src/pages/home.tsx

The layout was broken after moving to chakra.
I just wrapped the box in a `Container` element.

fix: fix setup ssh view layout

---

client/src/pages/create-app.tsx
client/src/pages/create-database.tsx

There was an issue with the create button for apps, it was triggering the form's default behavior which resulted in a page reload.
The PR also includes a fix to prevent issues with the databases create button.

fix(client): fix create app and database button

---

ledokku-bootstrap.sh
website/docs/advanced/manual-installation.mdx
website/docs/upgrade.md

I manually tested on a new DO droplet and it worked 🎉 
Closes #284

chore(installation): une new dokku git:from-image command

---

.eslintrc.js
server/src/queues/createDatabase.ts
server/src/queues/restartApp.ts
server/src/queues/synchroniseServer.ts
server/src/queues/unsetEnvVar.ts

Seeing all the warnings in the github diffs was stressing me out 😅

chore: set no-unused-vars eslint rule to error

---

client/package.json
client/src/Router.tsx
client/src/index.tsx
client/src/modules/app/AppRebuild.tsx
client/src/modules/app/AppRestart.tsx
client/src/modules/appProxyPorts/AddAppProxyPorts.tsx
client/src/modules/appProxyPorts/AppProxyPorts.tsx
client/src/modules/domains/AddAppDomain.tsx
client/src/modules/domains/AppDomains.tsx
client/src/pages/app/env.tsx
client/src/pages/app/index.tsx
client/src/pages/app/settings.tsx
client/src/pages/create-app.tsx
client/src/pages/create-database.tsx
client/src/pages/database/index.tsx
client/src/pages/database/settings.tsx
client/src/pages/utils.ts
client/src/ui/toast.ts
yarn.lock

closes : https://github.com/ledokku/ledokku/issues/266
Migrated all toasts to Chakra Ui 
In utils added config file that is reusable so in components we have to just add description. 
Screenshots below

chore(client): migrate toast messages to chakra UI

---

client/src/generated/graphql.tsx
client/src/graphql/queries/database.graphql
client/src/modules/database/DatabaseHeaderInfo.tsx
client/src/modules/database/DatabaseHeaderTabNav.tsx
client/src/pages/database/index.tsx
client/src/pages/database/logs.tsx
client/src/pages/database/settings.tsx
client/src/pages/utils.ts
server/package.json
server/prisma/migrations/20210312140904_add_database_version/migration.sql
server/prisma/schema.prisma
server/src/generated/graphql.ts
server/src/index.ts
server/src/lib/dokku/index.ts
server/src/lib/dokku/plugin/database/infoVersion.ts
server/src/queues/createDatabase.ts
server/src/queues/synchroniseServer.ts

- display the new header
- save the database version in our db

feat: database header redesign

---

client/package.json
client/src/index.tsx
yarn.lock

For better style across the app 🚀

feat: disable outline style for non keyboard users

---

client/src/modules/home/HomeHeaderTabNav.tsx
client/src/pages/activity.tsx
client/src/pages/dashboard.tsx
client/src/pages/metrics.tsx
client/src/pages/settings.tsx

chore: create shared home nav component

---

client/src/modules/app/AppHeaderTabNav.tsx
client/src/pages/app/env.tsx
client/src/pages/app/index.tsx
client/src/pages/app/logs.tsx
client/src/pages/app/settings.tsx

chore: create shared app nav component

---

server/src/graphql/mutations/addAppProxyPort.ts
server/src/graphql/mutations/addDomain.ts
server/src/graphql/mutations/createApp.ts
server/src/graphql/mutations/createDatabase.ts
server/src/graphql/mutations/destroyApp.ts
server/src/graphql/mutations/destroyDatabase.ts
server/src/graphql/mutations/removeAppProxyPort.ts
server/src/graphql/mutations/removeDomain.ts
server/src/graphql/mutations/setDomain.ts
server/src/graphql/queries/appLogs.ts
server/src/graphql/queries/appProxyPorts.ts
server/src/graphql/queries/databaseInfo.ts
server/src/graphql/queries/databaseLogs.ts
server/src/graphql/queries/dokkuPlugins.ts
server/src/graphql/queries/domains.ts
server/src/graphql/queries/envVars.ts
server/src/graphql/queries/isPluginInstalled.ts
server/src/queues/createDatabase.ts
server/src/queues/linkDatabase.ts
server/src/queues/rebuildApp.ts
server/src/queues/restartApp.ts
server/src/queues/setEnvVar.ts
server/src/queues/unlinkDatabase.ts
server/src/queues/unsetEnvVar.ts

closes  : https://github.com/ledokku/ledokku/issues/300

chore(server): add ssh.dispose to queues

---

client/package.json
client/src/generated/graphql.tsx
client/src/graphql/queries/dashboard.graphql
client/src/modules/app/AppHeaderInfo.tsx
client/src/pages/app/env.tsx
client/src/pages/app/index.tsx
client/src/pages/app/logs.tsx
client/src/pages/app/settings.tsx
client/src/pages/dashboard.tsx
client/src/ui/icons/GithubIcon.tsx
yarn.lock

Not a lot of info available so I made it simple

feat: app header redesign

---

website/docs/security.md
website/sidebars.js

docs: add security section

---

client/src/config.ts
website/docs/advanced/configuration.md

chore(client): fix how config is loaded

---

client/src/Router.tsx
client/src/modules/app/AppHeaderTabNav.tsx
client/src/modules/app/AppSettingsMenu.tsx
client/src/modules/appProxyPorts/AppProxyPorts.tsx
client/src/modules/domains/AppDomains.tsx
client/src/pages/app/settings.tsx
client/src/pages/app/settings/advanced.tsx
client/src/pages/app/settings/domains.tsx
client/src/pages/app/settings/ports.tsx

feat(client): redesign app settings

---

client/package.json
client/src/pages/app-creation/create-app-github.tsx
client/src/pages/app-creation/create-app.tsx
client/src/pages/create-database.tsx
yarn.lock

chore(client): replace react-feather with react-icons

---

client/src/ui/toast.ts

Accept a second parameter to overwrite the options

chore(client): add options to useToast component

---

client/src/generated/graphql.tsx
client/src/modules/domains/AddAppDomain.tsx
client/src/modules/domains/AppDomains.tsx
server/src/generated/graphql.ts
server/src/index.ts
server/src/lib/dokku/domains/report.ts

chore(client): migrate domains view to chakra

---

website/docs/security.md

Swapping over to a gender neutral pronoun

fix(docs): Update security.md

---

client/src/pages/home.tsx
yarn.lock

fix(client): fix Github app creation glitch

---

website/docs/uninstall.md

Fixed a typo, made the link to dokku more prominent and simplified the whole section.

chore: Update uninstall.md

---

ledokku-bootstrap.sh

- Colors via `tput` (An inbuilt Linux colour)
- using `Whiptail` ( An inbuilt Linux utility for better TUI experience)
- Gathering sys info, for providing detailed error messages
- Making the script run as root or sudo. (Some providers does not allow passwordless sudo)
- Updating System (The one-click dokku installation in Digital Ocean is so outdated)
- Installing Dokku using the script (If Dokku does not exist)
- Intro Comments
- Added Color to echo commands during installation
- Added newly defined functions to the main function

feat: improve ledokku installation script

---

website/docs/getting-started.mdx
website/docs/installation.mdx

This removes the redundant Dokku install part.
Can only be merged after : https://github.com/ledokku/ledokku/pull/393

docs: remove redundant dokku install part
